### ISSUE TITLE
Cartes pas traduites, mais version française bien présente sur YugiPedia

### ISSUE THREAD

**Issue by burnout293** [speedi57/YgoProFrPatcher#1]
Bonjour,

J'ai trouvé quelques cartes qui ne sont pas traduites alors que YugiPedia contient bien leur version française. Par exemple celle-ci [https://yugipedia.com/wiki/Endymion,_the_Mighty_Master_of_Magic](url) et visiblement les autres nouvelles cartes Pendulum aussi.
Si besoin de plus d'info, je me tiens à disposition.

**Comment by bthidev** [comment]
Je pense voir d'où ça vient, ça devrait être fixé d'ici demain

**Comment by yeagear** [comment]
les monstre mekk-chevalier sont pas traduit

**Comment by bthidev** [comment]
probleme corrigé

**Comment by burnout293** [comment]
Merci =D Vous êtes des chefs ! Ou "Tu" si tu es tout seul ^^

**Comment by bthidev** [comment]
pas de soucis :)

**Comment by burnout293** [comment]
Ah mince, je suis désolé j'annonce une mauvaise nouvelle x) Certaines cartes pendules n'ont que l'effet Magie d'écrit. (ex : Maitre Cerbère, Bête Mythique)
Par contre d'autres comportent bien les 2 effets (ex : Magicien Dragonfosse)

**Comment by burnout293** [comment]
Ah et il reste des cartes pas entièrement traduites. (ex : Licorne Majesspectre - Kirin)

**Comment by bthidev** [comment]
c'etais trop beaux, je regarde ça demain

**Comment by burnout293** [comment]
Merci. Dis moi si je peux aider et comment.

**Comment by bthidev** [comment]
Le mieux sa serais de faire une decklist avec des cartes maltraduite et me les envoyer

**Comment by burnout293** [comment]
Wouah ! Ok je viens juste de faire une recherche dans YGO Percy en allant dans la gestion de deck et en tapant "Monster" et j'ai obtenu 422 résultats xD https://i.imgur.com/SXKwOFW.jpg 
Pas sur qu'elle soit faisable la decklist.
J'ai regarder quelques cartes au hasard. Certaines sont en effet pas encore traduites sur yugipedia (ex: Hope Magician) mais d'autres le sont bien (ex : Ushi Oni)

**Comment by bthidev** [comment]
les carte cité sont bien traduite, a voir si il en manque pas d'autre

**Comment by burnout293** [comment]
pff ... ca me fait ch... de te faire encore bosser pour ca. Donc t'sais quoi, moi ca me convient très bien =) Merci bro

**Comment by bthidev** [comment]
Pas de soucis :)
