### ISSUE TITLE
Traduction et bug

### ISSUE THREAD

**Issue by Merlinpinpin58** [speedi57/YgoProFrPatcher#2]
Bonjour,

la carte striker dragon n'est pas traduit en français.

sur mon système (windows 10 x64 pro), sur les cartes pendules ce n'est pas marqué zone pendule et effet monstre mais le $...

Je ne sais pas si cela vient de vous où de percy

Cordialement
Merlinpinpin58

**Comment by bthidev** [comment]
Problème corrigé
