### ISSUE TITLE
Problème de traduction

### ISSUE THREAD

**Issue by Merlinpinpin58** [speedi57/YgoProFrPatcher#3]
Bonjour,

Pratiquement toutes les cartes sont en anglais alors que j'ai choisi la langue française.

Cordialement

**Comment by bthidev** [comment]
le lanceur doit être ouvert avec ygopro coupé après seulement il faut lancé ygopro, il faut attendre un peu sur la page principale qui est la notification des nouvelles carte.
Tu auras un point d'exclamation qui va se mettre en haut à droite.
j'ai vérifié toutes les cartes sont bien traduites actuellement
